### ISSUE TITLE
Use secret key instead of username/password?

### ISSUE THREAD

**Issue by wfgilman** [CultivateHQ/basic_auth#25]
I was looking for a library just like this. It looks like it will fit my needs, except that I'd like to use an API key instead of a username and password combination. Any interest in adding that functionality?

**Comment by paulanthonywilson** [comment]
@wfgilman Sorry - been away. Don't think that would be too tricky; I'll have a shot.

**Comment by paulanthonywilson** [comment]
Hi @wfgilman,

We started incorporating the idea of a key into this library, but changed our minds. The problem is that if we are looking for an API key, we are no longer doing [Basic Authentication](https://tools.ietf.org/html/rfc7617); it doesn't seem appropriate to then support it.

It would be pretty simple just to extract the key from a header. See [this example](https://github.com/CultivateHQ/basic_auth_scaffold/blob/master/lib/basic_auth_scaffold/token_only_router.ex).

Sorry, Paul
